import { loadCsv } from "./csv";
import type { GameData } from "./types";

const num = (v: string, fallback = 0) => (v === "" ? fallback : Number(v));
const numOrNull = (v: string) => (v === "" ? null : Number(v));
const bool = (v: string) => v.trim().toUpperCase() === "TRUE";

export async function loadGameData(): Promise<GameData> {
  const [
    effects,
    grades,
    texts,
    dailyPool,
    poolBonusEffects,
    locations,
    branches,
    minigames,
    minigameRewards,
    combats,
    levelups,
    skills,
    gauges,
    phases,
    contentTypes,
    milestones,
    currencies,
    passives,
    uiTextRows,
  ] = await Promise.all([
    loadCsv("effect_config"),
    loadCsv("grade_config"),
    loadCsv("event_text_pool"),
    loadCsv("daily_roll_pool"),
    loadCsv("daily_pool_bonus_effects"),
    loadCsv("location_config"),
    loadCsv("branch_config"),
    loadCsv("minigame_config"),
    loadCsv("minigame_reward_pool"),
    loadCsv("combat_trigger_config"),
    loadCsv("levelup_config"),
    loadCsv("skill_config"),
    loadCsv("gauge_config"),
    loadCsv("progression_phase_config"),
    loadCsv("content_type_config"),
    loadCsv("milestone_config"),
    loadCsv("currency_config"),
    loadCsv("passive_item_config"),
    loadCsv("ui_text_config"),
  ]);

  return {
    effects: effects.map((r) => ({
      effect_id: r.effect_id,
      effect_type: r.effect_type as any,
      target: r.target,
      value: num(r.value),
      value_type: r.value_type as any,
      skill_id: r.skill_id,
      icon: r.icon,
      description: r.description,
    })),
    grades: grades.map((r) => ({
      grade_id: r.grade_id,
      grade_name: r.grade_name,
      weight: num(r.weight),
      banner_color: r.banner_color,
      card_bg_color: r.card_bg_color,
      counter_cap: numOrNull(r.counter_cap),
      is_negative: bool(r.is_negative),
    })),
    texts: texts.map((r) => ({
      text_id: r.text_id,
      category: r.category,
      grade_id: r.grade_id,
      body: r.body,
    })),
    dailyPool: dailyPool.map((r) => ({
      pool_id: r.pool_id,
      grade_id: r.grade_id,
      text_id: r.text_id,
      effect_id: r.effect_id,
      weight: num(r.weight),
    })),
    poolBonusEffects: poolBonusEffects.map((r) => ({
      pool_id: r.pool_id,
      effect_id: r.effect_id,
    })),
    locations: locations.map((r) => ({
      location_id: r.location_id,
      name: r.name,
      text_id: r.text_id,
      entry_path: r.entry_path as any,
      grade_id: r.grade_id,
      repeatable: bool(r.repeatable),
      linked_effect_id: r.linked_effect_id,
      linked_minigame_id: r.linked_minigame_id,
      milestone_id: r.milestone_id,
    })),
    branches: branches.map((r) => ({
      branch_id: r.branch_id,
      subtype: r.subtype,
      text_id: r.text_id,
      option_a_label: r.option_a_label,
      option_a_effect_id: r.option_a_effect_id,
      option_a_prob: numOrNull(r.option_a_prob),
      option_b_label: r.option_b_label,
      option_b_effect_id: r.option_b_effect_id,
      option_b_prob: numOrNull(r.option_b_prob),
      cost_effect_id: r.cost_effect_id,
    })),
    minigames: minigames.map((r) => ({
      minigame_id: r.minigame_id,
      minigame_name: r.minigame_name,
      type: r.type,
      attempt_limit: numOrNull(r.attempt_limit),
    })),
    minigameRewards: minigameRewards.map((r) => ({
      reward_id: r.reward_id,
      minigame_id: r.minigame_id,
      effect_id: r.effect_id,
      weight: num(r.weight),
      label: r.label,
      color: r.color,
      action: r.action || "NORMAL",
    })),
    combats: combats.map((r) => ({
      combat_id: r.combat_id,
      tier: r.tier,
      text_id: r.text_id,
      gold_min: num(r.gold_min),
      gold_max: num(r.gold_max),
      exp_min: num(r.exp_min),
      exp_max: num(r.exp_max),
    })),
    levelups: levelups.map((r) => ({
      level: num(r.level),
      skill_grant_mode: r.skill_grant_mode as any,
      skill_pool_tier: r.skill_pool_tier,
      hp_heal_pct: num(r.hp_heal_pct, 5),
      exp_to_next: num(r.exp_to_next, 100),
    })),
    skills: skills.map((r) => ({
      skill_id: r.skill_id,
      skill_name: r.skill_name,
      tier: r.tier,
      is_upgrade: bool(r.is_upgrade),
      base_skill_id: r.base_skill_id,
      icon: r.icon,
      effect_text: r.effect_text,
    })),
    gauges: gauges.map((r) => ({
      gauge_id: r.gauge_id,
      grade_id: r.grade_id,
      cap: num(r.cap),
      icon: r.icon,
      reward_minigame_id: r.reward_minigame_id,
    })),
    phases: phases.map((r) => ({
      phase_id: r.phase_id,
      day_start: num(r.day_start),
      day_end: num(r.day_end),
      combat_weight: num(r.combat_weight),
      content_weight: num(r.content_weight),
    })),
    contentTypes: contentTypes.map((r) => ({
      type_id: r.type_id,
      type_name: r.type_name,
      weight: num(r.weight),
    })),
    uiTexts: Object.fromEntries(uiTextRows.map((r) => [r.key, r.text])),
    currencies: currencies.map((r) => ({
      currency_id: r.currency_id,
      state_key: r.state_key,
      icon: r.icon,
      label: r.label,
      always_show: bool(r.always_show),
    })),
    passives: passives.map((r) => ({
      item_id: r.item_id,
      item_name: r.item_name,
      icon: r.icon,
      effect_type: r.effect_type,
      effect_value: r.effect_value,
      owned_at_start: bool(r.owned_at_start),
      description: r.description,
    })),
    milestones: milestones.map((r) => ({
      milestone_id: r.milestone_id,
      milestone_name: r.milestone_name,
      currency: r.currency,
      cap: num(r.cap),
      tier1_effect: r.tier1_effect,
      tier1_at: num(r.tier1_at),
      tier2_effect: r.tier2_effect,
      tier2_at: num(r.tier2_at),
    })),
  };
}
